### ISSUE TITLE
Attempting to throw Secret Pass freezes the game (Duckstation)

### ISSUE THREAD

**Issue by Feldherren** [Dinopony/alundra-randomizer#58] opened 2022-11-15 22:43 UTC
In my game, the secret pass randomised into Lurvy's Shop. You can pick the Secret Pass up fine, but the game freezes as soon as you attempt to throw it over to Lurvy to buy it.
Not sure if this happens if it randomises into the Inoa shop.

**Comment by Dinopony** [comment] 2023-09-26 07:45
Most likely a duplicate of https://github.com/Dinopony/alundra-randomizer/issues/59

**Closed as completed by Dinopony** 2023-09-26 07:45 UTC
