### ISSUE TITLE
Attempting to throw Broken Armor AND Tree Gem in Lurvy's shop freezes the game and/or moves item off screen

### ISSUE THREAD

**Issue by buuf** [Dinopony/alundra-randomizer#60] opened 2023-01-29 00:41 UTC
permalink": "aG14SbsX8QL1pJJJLqqS+ktJUD0UKEIfSSSSVJVX/YkJBlJVBmXBT+gCCiDA5B2D0AgYBBCIJBoA=/",

**Comment by buuf** [comment] 2023-02-12 23:01
I think I found a workaround... it involves jump throwing the items near lurvy in the hope something picks it up and drops it on the table to be sold.

**Comment by Dinopony** [comment] 2023-09-26 07:45
Duplicate of https://github.com/Dinopony/alundra-randomizer/issues/59

**Closed as completed by Dinopony** 2023-09-26 07:45 UTC
